#:schema node_modules/wrangler/config-schema.json
name = "example-nextjs-on-pages"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
# [placement]
# mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "checking"
database_id = "a93ba994-efe4-47ae-84f8-59c16d60a2e7"
migrations_dir = ".drizzle-out"