# Your wrangler.toml file should look something like this:
name = "d1project"
compatibility_date = "2025-01-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# WARNING: When running a production build locally using Wrangler, be aware that the .env file may be omitted. Therefore, ensure that you have the same environment variables in your wrangler.toml file.
# However, you don't have to include Drizzle environment unless you want to access `drizzle-kit` commands in the deployed code.
[vars]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tutorial_drizzle_d1"
database_id = "b77a427d-9331-47b7-aaa0-659f10273f5c"
preview_database_id = "DB"
